name: publish-container-image

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CONTAINER_REGISTRY_USERNAME: ${GITHUB_ACTOR}
      CONTAINER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('./**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build necessary modules
        run: mvn install -pl context-monitoring -am

      - name: Get short commit SHA
        if: ${{ github.event_name == 'push' }}
        id: get_short_commit_SHA
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Build Image
        if: ${{ github.event_name == 'push' }}
        env:
          IMAGE_TAG: ${{ steps.get_short_commit_SHA.outputs.sha8}}
        run: mvn compile jib:build -pl smartclide-monitoring -Djib.to.auth.username="${CONTAINER_REGISTRY_USERNAME}" -Djib.to.auth.password="${CONTAINER_REGISTRY_TOKEN}" -Djib.to.tags="${IMAGE_TAG}"

      # below code triggers only for release events

      - name: Get release name
        if: ${{ github.event_name == 'release' }}
        id: get_release_name
        run: |
          echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}"
          echo "::set-output name=TAG2_NAME::${{ github.event.release.name }}"

      - name: Build Image for Release
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        env:
          IMAGE_TAG: ${{ github.event.release.name }}
          TEST: ${{ steps.get_release_name.outputs.TAG2_NAME }}
          RELEASES_NAME: ${{ steps.get_release_name.outputs.RELEASES_NAME }}
          RELEASE_NAME: ${{ steps.get_release_name.outputs.RELEASE_NAME }}
          RELEASES1_NAME: ${{ steps.get_release_name.outputs.RELEASES1_NAME }}
          RELEASE1_NAME: ${{ steps.get_release_name.outputs.RELEASE1_NAME }}
        run: |
          echo "image tag name is $IMAGE_TAG"
          echo "test name is $TEST"
          echo "releases name is $RELEASES_NAME"
          echo "release name is $RELEASE_NAME"
          echo "releases1 name is $RELEASES1_NAME"
          echo "release1 name is $RELEASE1_NAME"
          echo "github release event-tag name ${{ github.event.release.tag_name }}"
          echo "github release event-name ${{ github.event.release.name }}"
          mvn compile jib:build -pl smartclide-monitoring -Djib.to.auth.username="${CONTAINER_REGISTRY_USERNAME}" -Djib.to.auth.password="${CONTAINER_REGISTRY_TOKEN}" -Djib.to.tags="${IMAGE_TAG}"
