name: build-container-image

on:
  push:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CONTAINER_REGISTRY_USERNAME: ${GITHUB_ACTOR}
      CONTAINER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('./**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build necessary modules
        run: mvn install -pl context-monitoring -am

      - name: Get latest release info
        if: ${{ github.event_name == 'release' }}
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: get image tag
        id: get_image_tag
        run: |
          if ${{ github.event_name == 'push' }}; then
            echo "::set-output name=imageTag::$(echo ${GITHUB_SHA} | cut -c1-8)"
          fi
          if ${{ github.event_name == 'release' }}; then
            echo "::set-output name=imageTag::$(echo ${ steps.latest_release_info.outputs.name })"
          fi

      - name: Build Image
        env:
          IMAGE_TAG: ${{ steps.get_image_tag.outputs.imageTag}}
        run: mvn compile jib:build -pl smartclide-monitoring -Djib.to.auth.username="${CONTAINER_REGISTRY_USERNAME}" -Djib.to.auth.password="${CONTAINER_REGISTRY_TOKEN}" -Djib.to.tags="${IMAGE_TAG}"
